services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: eidoox
      MONGO_INITDB_ROOT_PASSWORD: eidoox99
    ports:
      - "27017:27017"
    volumes:
      - mongo-social-data:/data/db

volumes:
  mongo-social-data:
    driver: local
